import {
  AutomationRule,
  ClassGroup,
  EvaluationItem,
  HomeworkItem,
  Project,
  QuestionItem,
  Report,
  RevisionPlan,
  Session,
  Student,
  Tutor,
} from "./types";

export const tutors: Tutor[] = [
  {
    id: "t1",
    name: "Amelia Carter",
    email: "amelia.carter@academy.io",
    role: "Lead Tutor",
  },
  {
    id: "t2",
    name: "Marcus Singh",
    email: "marcus.singh@academy.io",
    role: "Tutor",
  },
  {
    id: "t3",
    name: "Priya Desai",
    email: "priya.desai@academy.io",
    role: "Instructional Coach",
  },
  {
    id: "t4",
    name: "Leo Martinez",
    email: "leo.martinez@academy.io",
    role: "Tutor",
  },
  {
    id: "t5",
    name: "Isabella Moore",
    email: "isabella.moore@academy.io",
    role: "Tutor",
  },
  {
    id: "t6",
    name: "Harper Lee",
    email: "harper.lee@academy.io",
    role: "Tutor",
  },
  {
    id: "t7",
    name: "Ethan Brooks",
    email: "ethan.brooks@academy.io",
    role: "Instructional Coach",
  },
  {
    id: "t8",
    name: "Naomi Chen",
    email: "naomi.chen@academy.io",
    role: "Tutor",
  },
];

export const classes: ClassGroup[] = [
  {
    id: "c1",
    name: "Algebra II - Cohort A",
    subject: "Mathematics",
    level: "Grade 10",
    schedule: "8:30 AM · Mon/Wed",
    tutorId: "t1",
    studentCount: 14,
    riskLevel: "medium",
  },
  {
    id: "c2",
    name: "Biology Foundations",
    subject: "Science",
    level: "Grade 9",
    schedule: "10:00 AM · Tue/Thu",
    tutorId: "t2",
    studentCount: 18,
    riskLevel: "low",
  },
  {
    id: "c3",
    name: "World History Seminar",
    subject: "History",
    level: "Grade 11",
    schedule: "1:00 PM · Mon/Wed",
    tutorId: "t3",
    studentCount: 12,
    riskLevel: "high",
  },
  {
    id: "c4",
    name: "Chemistry Honors",
    subject: "Science",
    level: "Grade 11",
    schedule: "3:00 PM · Tue/Thu",
    tutorId: "t1",
    studentCount: 16,
    riskLevel: "medium",
  },
  {
    id: "c5",
    name: "Geometry Skills Lab",
    subject: "Mathematics",
    level: "Grade 9",
    schedule: "9:30 AM · Fri",
    tutorId: "t2",
    studentCount: 20,
    riskLevel: "low",
  },
  {
    id: "c6",
    name: "AP Literature Seminar",
    subject: "English",
    level: "Grade 12",
    schedule: "4:00 PM · Mon",
    tutorId: "t5",
    studentCount: 11,
    riskLevel: "low",
  },
  {
    id: "c7",
    name: "Physics Problem Solving",
    subject: "Science",
    level: "Grade 12",
    schedule: "11:00 AM · Fri",
    tutorId: "t4",
    studentCount: 13,
    riskLevel: "medium",
  },
  {
    id: "c8",
    name: "Spanish Conversation Lab",
    subject: "Languages",
    level: "Grade 10",
    schedule: "2:00 PM · Tue/Thu",
    tutorId: "t6",
    studentCount: 15,
    riskLevel: "low",
  },
  {
    id: "c9",
    name: "Data Literacy Bootcamp",
    subject: "Technology",
    level: "Grade 11",
    schedule: "5:00 PM · Wed",
    tutorId: "t8",
    studentCount: 17,
    riskLevel: "medium",
  },
];

export const sessions: Session[] = [
  {
    id: "s1",
    time: "08:30",
    classId: "c1",
    focus: "Quadratic functions",
    status: "live",
    joinUrl: "#",
  },
  {
    id: "s2",
    time: "10:00",
    classId: "c2",
    focus: "Cell structures review",
    status: "upcoming",
    joinUrl: "#",
  },
  {
    id: "s3",
    time: "11:30",
    classId: "c4",
    focus: "Stoichiometry workshop",
    status: "upcoming",
    joinUrl: "#",
  },
  {
    id: "s4",
    time: "13:00",
    classId: "c3",
    focus: "Revolutions case studies",
    status: "upcoming",
    joinUrl: "#",
  },
  {
    id: "s5",
    time: "15:30",
    classId: "c5",
    focus: "Coordinate proofs",
    status: "upcoming",
    joinUrl: "#",
  },
  {
    id: "s6",
    time: "16:00",
    classId: "c6",
    focus: "Rhetorical devices",
    status: "upcoming",
    joinUrl: "#",
  },
  {
    id: "s7",
    time: "11:00",
    classId: "c7",
    focus: "Forces and momentum",
    status: "upcoming",
    joinUrl: "#",
  },
  {
    id: "s8",
    time: "17:00",
    classId: "c9",
    focus: "Data cleaning lab",
    status: "upcoming",
    joinUrl: "#",
  },
];

export const students: Student[] = [
  {
    id: "stu1",
    name: "Lina Ortega",
    cohortId: "c1",
    mastery: 72,
    flagged: true,
    recentErrors: ["Factoring expressions", "Graph interpretation"],
    notes: "Needs modeling for completing the square.",
    growth: "Moderate",
  },
  {
    id: "stu2",
    name: "Jordan Park",
    cohortId: "c1",
    mastery: 88,
    recentErrors: ["Vertex form translation"],
    notes: "Responds well to visual scaffolds.",
    growth: "Strong",
  },
  {
    id: "stu3",
    name: "Emily Zhao",
    cohortId: "c2",
    mastery: 81,
    recentErrors: ["Mitosis sequencing"],
    notes: "Provide retrieval practice cards.",
    growth: "Moderate",
  },
  {
    id: "stu4",
    name: "Diego Ramirez",
    cohortId: "c3",
    mastery: 65,
    flagged: true,
    recentErrors: ["Cause/effect mapping"],
    notes: "Schedule quick oral check-in.",
    growth: "Low",
  },
  {
    id: "stu5",
    name: "Sofia Martins",
    cohortId: "c4",
    mastery: 92,
    recentErrors: ["Limiting reagents"],
    notes: "Ready for stretch problems.",
    growth: "Strong",
  },
  {
    id: "stu6",
    name: "Noah Patel",
    cohortId: "c5",
    mastery: 77,
    recentErrors: ["Polygon similarity"],
    notes: "Pair with peer coach.",
    growth: "Moderate",
  },
  {
    id: "stu7",
    name: "Ava Johnson",
    cohortId: "c2",
    mastery: 69,
    flagged: true,
    recentErrors: ["Organelle functions"],
    notes: "Recommend extra practice set.",
    growth: "Low",
  },
  {
    id: "stu8",
    name: "Mateo Silva",
    cohortId: "c3",
    mastery: 74,
    recentErrors: ["Document sourcing"],
    notes: "Use guided annotation.",
    growth: "Moderate",
  },
  {
    id: "stu9",
    name: "Hana Kim",
    cohortId: "c4",
    mastery: 83,
    recentErrors: ["Balancing equations"],
    notes: "Provide exit tickets weekly.",
    growth: "Moderate",
  },
  {
    id: "stu10",
    name: "Olivia Bennett",
    cohortId: "c6",
    mastery: 90,
    recentErrors: ["Poetic devices"],
    notes: "Push for AP-level analysis.",
    growth: "Strong",
  },
  {
    id: "stu11",
    name: "Ravi Kulkarni",
    cohortId: "c7",
    mastery: 71,
    flagged: true,
    recentErrors: ["Impulse calculations"],
    notes: "Use manipulatives for momentum.",
    growth: "Moderate",
  },
  {
    id: "stu12",
    name: "Camila Torres",
    cohortId: "c8",
    mastery: 79,
    recentErrors: ["Verb conjugations"],
    notes: "Add speaking drills at start.",
    growth: "Moderate",
  },
];

export const homeworkItems: HomeworkItem[] = [
  {
    id: "h1",
    title: "Factoring practice set",
    classId: "c1",
    dueDate: "Today",
    status: "pending",
    submissions: 12,
  },
  {
    id: "h2",
    title: "Cell structure slide deck",
    classId: "c2",
    dueDate: "Tomorrow",
    status: "pending",
    submissions: 9,
  },
  {
    id: "h3",
    title: "Primary sources reflection",
    classId: "c3",
    dueDate: "Today",
    status: "scheduled",
    submissions: 10,
  },
  {
    id: "h4",
    title: "Stoichiometry worksheet",
    classId: "c4",
    dueDate: "Fri",
    status: "scheduled",
    submissions: 14,
  },
  {
    id: "h5",
    title: "Polygon proofs",
    classId: "c5",
    dueDate: "Today",
    status: "completed",
    submissions: 18,
  },
  {
    id: "h6",
    title: "Vertex form quiz corrections",
    classId: "c1",
    dueDate: "Thu",
    status: "completed",
    submissions: 14,
  },
  {
    id: "h7",
    title: "Literature response journal",
    classId: "c6",
    dueDate: "Mon",
    status: "scheduled",
    submissions: 7,
  },
  {
    id: "h8",
    title: "Momentum problem set",
    classId: "c7",
    dueDate: "Tomorrow",
    status: "pending",
    submissions: 11,
  },
  {
    id: "h9",
    title: "Data visualization critique",
    classId: "c9",
    dueDate: "Fri",
    status: "pending",
    submissions: 10,
  },
];

export const evaluationItems: EvaluationItem[] = [
  {
    id: "e1",
    studentId: "stu1",
    evaluator: "Amelia Carter",
    submittedAt: "8:15 AM",
    status: "pending",
    focus: "Algebra misconceptions",
  },
  {
    id: "e2",
    studentId: "stu4",
    evaluator: "Priya Desai",
    submittedAt: "Yesterday",
    status: "in_review",
    focus: "Historical analysis",
  },
  {
    id: "e3",
    studentId: "stu2",
    evaluator: "Marcus Singh",
    submittedAt: "Yesterday",
    status: "pending",
    focus: "Problem solving",
  },
  {
    id: "e4",
    studentId: "stu7",
    evaluator: "Marcus Singh",
    submittedAt: "Today",
    status: "pending",
    focus: "Concept recall",
  },
  {
    id: "e5",
    studentId: "stu9",
    evaluator: "Amelia Carter",
    submittedAt: "Today",
    status: "completed",
    focus: "Lab safety",
  },
  {
    id: "e6",
    studentId: "stu10",
    evaluator: "Isabella Moore",
    submittedAt: "Today",
    status: "pending",
    focus: "AP discussion",
  },
  {
    id: "e7",
    studentId: "stu11",
    evaluator: "Leo Martinez",
    submittedAt: "Today",
    status: "in_review",
    focus: "Momentum",
  },
  {
    id: "e8",
    studentId: "stu12",
    evaluator: "Harper Lee",
    submittedAt: "Today",
    status: "pending",
    focus: "Fluency",
  },
];

export const questionBank: QuestionItem[] = [
  {
    id: "q1",
    type: "MCQ",
    prompt: "Identify the vertex of y = (x-3)^2 + 4",
    difficulty: "Easy",
    tags: ["Algebra", "Graphs"],
    updatedAt: "Today",
  },
  {
    id: "q2",
    type: "MCQ",
    prompt: "Which organelle synthesizes proteins?",
    difficulty: "Easy",
    tags: ["Biology", "Cells"],
    updatedAt: "Yesterday",
  },
  {
    id: "q3",
    type: "Case Study",
    prompt: "Analyze the causes of the 1911 Revolution in China.",
    difficulty: "Hard",
    tags: ["History", "Analysis"],
    updatedAt: "Mon",
  },
  {
    id: "q4",
    type: "Short Answer",
    prompt: "Balance the equation: Fe + O2 -> Fe2O3",
    difficulty: "Medium",
    tags: ["Chemistry", "Reactions"],
    updatedAt: "Tue",
  },
  {
    id: "q5",
    type: "Case Study",
    prompt: "Design a lab to test osmosis in plant cells.",
    difficulty: "Hard",
    tags: ["Biology", "Investigation"],
    updatedAt: "Today",
  },
  {
    id: "q6",
    type: "MCQ",
    prompt: "Which theorem proves two lines are parallel?",
    difficulty: "Medium",
    tags: ["Geometry", "Proofs"],
    updatedAt: "Wed",
  },
  {
    id: "q7",
    type: "Short Answer",
    prompt: "Explain the role of catalysts in reactions.",
    difficulty: "Medium",
    tags: ["Chemistry", "Kinetics"],
    updatedAt: "Fri",
  },
  {
    id: "q8",
    type: "MCQ",
    prompt: "What is the discriminant of x^2 + 6x + 9?",
    difficulty: "Easy",
    tags: ["Algebra", "Quadratics"],
    updatedAt: "Today",
  },
  {
    id: "q9",
    type: "MCQ",
    prompt: "Which force diagram represents equilibrium?",
    difficulty: "Medium",
    tags: ["Physics", "Forces"],
    updatedAt: "Today",
  },
  {
    id: "q10",
    type: "Case Study",
    prompt: "Critique the ethical use of data in a public survey.",
    difficulty: "Hard",
    tags: ["Data Literacy", "Ethics"],
    updatedAt: "Today",
  },
];

export const revisionPlans: RevisionPlan[] = [
  {
    id: "r1",
    title: "Quadratics clarity sprint",
    studentId: "stu1",
    classId: "c1",
    focusAreas: ["Vertex form", "Factoring"],
    cadence: "3 sessions/week",
    owner: "Amelia",
    status: "active",
  },
  {
    id: "r2",
    title: "Source reliability bootcamp",
    studentId: "stu4",
    classId: "c3",
    focusAreas: ["Document sourcing", "Claim evidence"],
    cadence: "2 sessions/week",
    owner: "Priya",
    status: "draft",
  },
  {
    id: "r3",
    title: "Lab precision tune-up",
    classId: "c4",
    focusAreas: ["Molar ratios", "Safety checks"],
    cadence: "Weekly",
    owner: "Amelia",
    status: "active",
  },
  {
    id: "r4",
    title: "Geometry reasoning loop",
    classId: "c5",
    focusAreas: ["Similarity", "Proof writing"],
    cadence: "Bi-weekly",
    owner: "Marcus",
    status: "completed",
  },
  {
    id: "r5",
    title: "Cell structures refresh",
    classId: "c2",
    focusAreas: ["Organelles", "Processes"],
    cadence: "2 sessions/week",
    owner: "Marcus",
    status: "active",
  },
  {
    id: "r6",
    title: "Momentum mastery",
    classId: "c7",
    focusAreas: ["Impulse", "Collisions"],
    cadence: "3 sessions/week",
    owner: "Leo",
    status: "draft",
  },
  {
    id: "r7",
    title: "Textual analysis sprints",
    classId: "c6",
    focusAreas: ["Themes", "Evidence"],
    cadence: "Weekly",
    owner: "Isabella",
    status: "active",
  },
  {
    id: "r8",
    title: "Data storytelling",
    classId: "c9",
    focusAreas: ["Charts", "Interpretation"],
    cadence: "Bi-weekly",
    owner: "Naomi",
    status: "active",
  },
];

export const projects: Project[] = [
  {
    id: "p1",
    title: "Historical dossier",
    classId: "c3",
    dueDate: "Mar 28",
    milestones: [
      { label: "Source collection", date: "Mar 12", status: "done" },
      { label: "Thesis outline", date: "Mar 18", status: "in_progress" },
      { label: "Draft review", date: "Mar 24", status: "not_started" },
    ],
    rubric: [
      { criterion: "Evidence quality", weight: 40, met: true },
      { criterion: "Analysis depth", weight: 35, met: false },
      { criterion: "Citation accuracy", weight: 25, met: false },
    ],
  },
  {
    id: "p2",
    title: "Lab safety audit",
    classId: "c4",
    dueDate: "Apr 2",
    milestones: [
      { label: "Checklist draft", date: "Mar 15", status: "done" },
      { label: "Peer review", date: "Mar 20", status: "in_progress" },
      { label: "Final audit", date: "Apr 2", status: "not_started" },
    ],
    rubric: [
      { criterion: "Procedure clarity", weight: 40, met: true },
      { criterion: "Data integrity", weight: 30, met: true },
      { criterion: "Safety compliance", weight: 30, met: false },
    ],
  },
  {
    id: "p3",
    title: "STEM career case study",
    classId: "c2",
    dueDate: "Mar 30",
    milestones: [
      { label: "Interview plan", date: "Mar 17", status: "in_progress" },
      { label: "Draft slides", date: "Mar 25", status: "not_started" },
      { label: "Presentation", date: "Mar 30", status: "not_started" },
    ],
    rubric: [
      { criterion: "Content accuracy", weight: 45, met: false },
      { criterion: "Visual design", weight: 30, met: false },
      { criterion: "Delivery", weight: 25, met: false },
    ],
  },
  {
    id: "p4",
    title: "Physics lab notebook",
    classId: "c7",
    dueDate: "Apr 5",
    milestones: [
      { label: "Data tables", date: "Mar 22", status: "in_progress" },
      { label: "Error analysis", date: "Mar 29", status: "not_started" },
      { label: "Final review", date: "Apr 5", status: "not_started" },
    ],
    rubric: [
      { criterion: "Accuracy", weight: 40, met: false },
      { criterion: "Precision", weight: 30, met: false },
      { criterion: "Reflection", weight: 30, met: false },
    ],
  },
  {
    id: "p5",
    title: "AP Lit comparative essay",
    classId: "c6",
    dueDate: "Apr 10",
    milestones: [
      { label: "Outline", date: "Mar 25", status: "not_started" },
      { label: "Peer feedback", date: "Apr 2", status: "not_started" },
      { label: "Final draft", date: "Apr 10", status: "not_started" },
    ],
    rubric: [
      { criterion: "Thesis clarity", weight: 35, met: false },
      { criterion: "Evidence integration", weight: 40, met: false },
      { criterion: "Style", weight: 25, met: false },
    ],
  },
  {
    id: "p6",
    title: "Spanish culture presentation",
    classId: "c8",
    dueDate: "Apr 3",
    milestones: [
      { label: "Topic selection", date: "Mar 18", status: "done" },
      { label: "Script draft", date: "Mar 24", status: "in_progress" },
      { label: "Slides ready", date: "Apr 1", status: "not_started" },
    ],
    rubric: [
      { criterion: "Pronunciation", weight: 30, met: false },
      { criterion: "Cultural insight", weight: 40, met: false },
      { criterion: "Delivery", weight: 30, met: false },
    ],
  },
  {
    id: "p7",
    title: "Geometry design project",
    classId: "c5",
    dueDate: "Apr 8",
    milestones: [
      { label: "Blueprint draft", date: "Mar 27", status: "not_started" },
      { label: "Peer review", date: "Apr 3", status: "not_started" },
      { label: "Final render", date: "Apr 8", status: "not_started" },
    ],
    rubric: [
      { criterion: "Accuracy", weight: 50, met: false },
      { criterion: "Creativity", weight: 30, met: false },
      { criterion: "Presentation", weight: 20, met: false },
    ],
  },
  {
    id: "p8",
    title: "Data ethics brief",
    classId: "c9",
    dueDate: "Apr 12",
    milestones: [
      { label: "Research notes", date: "Mar 28", status: "not_started" },
      { label: "Draft review", date: "Apr 6", status: "not_started" },
      { label: "Final brief", date: "Apr 12", status: "not_started" },
    ],
    rubric: [
      { criterion: "Ethical stance", weight: 40, met: false },
      { criterion: "Evidence", weight: 35, met: false },
      { criterion: "Clarity", weight: 25, met: false },
    ],
  },
];

export const reports: Report[] = [
  {
    id: "rep1",
    audience: "Parent",
    studentId: "stu1",
    period: "This week",
    status: "ready",
    generatedAt: "Today 07:45",
  },
  {
    id: "rep2",
    audience: "Admin",
    classId: "c3",
    period: "This month",
    status: "draft",
    generatedAt: "Yesterday",
  },
  {
    id: "rep3",
    audience: "Tutor",
    classId: "c4",
    period: "This week",
    status: "sent",
    generatedAt: "Today 06:55",
  },
  {
    id: "rep4",
    audience: "Parent",
    studentId: "stu7",
    period: "This week",
    status: "ready",
    generatedAt: "Today 06:20",
  },
  {
    id: "rep5",
    audience: "Parent",
    studentId: "stu4",
    period: "This week",
    status: "draft",
    generatedAt: "Yesterday",
  },
  {
    id: "rep6",
    audience: "Admin",
    classId: "c7",
    period: "This month",
    status: "ready",
    generatedAt: "Today 05:45",
  },
  {
    id: "rep7",
    audience: "Tutor",
    classId: "c6",
    period: "This week",
    status: "sent",
    generatedAt: "Today 07:10",
  },
  {
    id: "rep8",
    audience: "Parent",
    studentId: "stu12",
    period: "This week",
    status: "ready",
    generatedAt: "Today 07:30",
  },
];

export const automationRules: AutomationRule[] = [
  {
    id: "a1",
    name: "Flag low quiz scores",
    trigger: "Score below 70%",
    action: "Create revision plan draft",
    channel: "In-app",
    status: "active",
    owner: "Amelia",
  },
  {
    id: "a2",
    name: "Parent reminder",
    trigger: "Homework overdue 48h",
    action: "Send summary",
    channel: "Email",
    status: "active",
    owner: "Marcus",
  },
  {
    id: "a3",
    name: "Check-in for flagged students",
    trigger: "New flag added",
    action: "Create tutor task",
    channel: "In-app",
    status: "paused",
    owner: "Priya",
  },
  {
    id: "a4",
    name: "Celebrate mastery jump",
    trigger: "Mastery +10pts",
    action: "Send encouragement",
    channel: "SMS",
    status: "active",
    owner: "Marcus",
  },
  {
    id: "a5",
    name: "Weekly report generator",
    trigger: "Fridays 4 PM",
    action: "Compile parent summaries",
    channel: "Email",
    status: "active",
    owner: "Amelia",
  },
  {
    id: "a6",
    name: "Lab safety follow-up",
    trigger: "Safety form missing",
    action: "Send reminder",
    channel: "SMS",
    status: "active",
    owner: "Isabella",
  },
  {
    id: "a7",
    name: "Data assignment alert",
    trigger: "New data project",
    action: "Notify tutors",
    channel: "In-app",
    status: "active",
    owner: "Naomi",
  },
  {
    id: "a8",
    name: "Language practice prompt",
    trigger: "No speaking practice in 7 days",
    action: "Create drill task",
    channel: "In-app",
    status: "paused",
    owner: "Harper",
  },
];
